select * from customer limit 20;

-- total revenue generated by male vs female customer --

select gender , sum(purchase_amount) as Revenue
from customer
group by gender;

--Which customer used discount but still spent more than the
--average purchase amount
select  customer_id , purchase_amount from customer
where discount_applied='Yes' 
and purchase_amount>(select avg(purchase_amount) from customer)
;
select avg(purchase_amount) from customer;

-- which are the top 5 products with hieghest 
--average rating

select item_purchased ,round(avg(review_rating::numeric),2) as "Average product rating"
from customer
group by item_purchased
order by avg(review_rating ) desc limit 5;

--compare the average purchase amount between 
--standard and express shipping
select shipping_type,
round(avg(purchase_amount) ,2)
from customer
where shipping_type 
in ('Standard', 'Express')
group by shipping_type;

--do subscribed customers spend more ? Compare average and total 
--revenue between sunscribers and non - subscribers

select  subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status 
order by total_revenue , avg_spend desc
;

--which product has highest percentage of purchases
--with discount applied
select 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        * 100.0 / COUNT(*), 
    2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;